version: 2
updates:
  - package-ecosystem: gradle
    directory: '/'
    schedule:
      interval: weekly
      time: "22:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: weekly
