[libraries]
junit-bom = { module = "org.junit:junit-bom", version = "5.11.3" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
hamcrest = { module = "org.hamcrest:hamcrest", version = "3.0" }
